"""drop column

Revision ID: fde449b03935
Revises: f9a0282afbe0
Create Date: 2018-03-30 16:56:39.985202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fde449b03935'
down_revision = 'f9a0282afbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'sql_user')
    op.drop_column('asset', 'sql_passwd')
    op.drop_column('script_task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_task', sa.Column('task_id', mysql.VARCHAR(length=90), nullable=True))
    op.add_column('asset', sa.Column('sql_passwd', mysql.VARCHAR(length=90), nullable=True))
    op.add_column('asset', sa.Column('sql_user', mysql.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
